Add 1-WPK day 5
camargodev/programming-challenges pull request #12
Opened 2022-06-18 04:26 UTC by camargodev

2022-06-18 06:37 UTC, jdalbosco requested changes

2022-06-18 06:37 UTC, jdalbosco commented on hackerrank/1-week-prep/day-5/balanced-brackets.py
> +        return self._values[self._size-1]
```suggestion
        return self._values[-1]
```

2022-06-18 06:37 UTC, jdalbosco commented on hackerrank/1-week-prep/day-5/merge-two-sorted-linked-lists.py
> +def mergeLists(head1, head2):
```suggestion
def merge_lists(head1, head2):
```

2022-06-18 06:37 UTC, jdalbosco commented on hackerrank/1-week-prep/day-5/merge-two-sorted-linked-lists.py
> +            current, last, head1 = consume_list(current, last, head1)
```suggestion
    if head1 is None:
        current.next = head2
    if head2 is None:
        current.next = head1
```

2022-06-18 06:37 UTC, jdalbosco commented on hackerrank/1-week-prep/day-5/mock-test-5.py
> +        occurrences[value] += 1
One of the constraints of the problem is that each `value` in `values` will be unique, so you didn't have to keep track of occurrences.

2022-06-18 06:37 UTC, jdalbosco commented on hackerrank/1-week-prep/day-5/mock-test-5.py
> +    return num_pairs//2
You can just validate each of the values with the previous - or the following - ones. No need to validate with both and then divide by two. 😸

2022-06-18 06:37 UTC, jdalbosco commented on hackerrank/1-week-prep/day-5/queue-using-two-stacks.py
> +        self._values.pop()
```suggestion
        self._size -= 1
        value = self._values.pop()
```

2022-06-18 06:37 UTC, jdalbosco commented on hackerrank/1-week-prep/day-5/queue-using-two-stacks.py
> +                self._stack_1.push(self._stack_2.pop())
Lines 34-36 and 40-42 are the same, maybe you could create a function for those operations.

2022-06-18 06:37 UTC, jdalbosco commented on hackerrank/1-week-prep/day-5/queue-using-two-stacks.py
> +        self._stack_2 = Stack()
Just a suggestion, but I think using more informative names for these stacks will improve readability.

2022-06-20 13:55 UTC, camargodev commented on hackerrank/1-week-prep/day-5/queue-using-two-stacks.py
> +                self._stack_1.push(self._stack_2.pop())
```suggestion
class Queue:
    def __init__(self):
        self._main_stack = Stack()
        self._helper_stack = Stack()
    
    def enqueue(self, new_value):
        if self._main_stack.is_empty() and self._helper_stack.is_empty():
            self._main_stack.push(new_value)
        else:
            self._helper_stack.push(new_value)
    
    def dequeue(self):
        self._move_to_main_stack()
        self._main_stack.pop()
    
    def print_front(self):
        self._move_to_main_stack()
        print(self._main_stack.top())
        
    def _move_to_main_stack(self):
        if not self._main_stack.is_empty():
            return
        while not self._helper_stack.is_empty():
            self._main_stack.push(self._helper_stack.pop())
```

2022-06-20 13:57 UTC, jdalbosco approved these changes

2022-06-20 13:57 UTC, jdalbosco commented on hackerrank/1-week-prep/day-5/queue-using-two-stacks.py
> +        print(self._stack_1.top())
```suggestion
```

2022-06-20 13:58 UTC, merged